// Code generated by protoc-gen-go.
// source: battle.proto
// DO NOT EDIT!

/*
Package vse is a generated protocol buffer package.

It is generated from these files:
	battle.proto
	common.proto

It has these top-level messages:
	NetId
	Player
	Players
	GridStep
	RollConfirm
	BeginShoot
	CreateMonster
	PlayerMove
	PlayerAttack
	PlayerHurt
	PlayerDead
	CreateBullet
	ShowBoss
	CleanMonster
	CreateEffect
	DestoryBoosBullet
	PlayInfo
	Position
	Rotation
*/
package vse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetId struct {
	NetId            *int32 `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NetId) Reset()                    { *m = NetId{} }
func (m *NetId) String() string            { return proto.CompactTextString(m) }
func (*NetId) ProtoMessage()               {}
func (*NetId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NetId) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

type Player struct {
	NetId            *int32 `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	ClientId         *int32 `protobuf:"varint,2,req,name=clientId" json:"clientId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Player) Reset()                    { *m = Player{} }
func (m *Player) String() string            { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()               {}
func (*Player) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Player) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *Player) GetClientId() int32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

type Players struct {
	List             []*Player `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
	Total            *int32    `protobuf:"varint,2,req,name=total" json:"total,omitempty"`
	MasterId         *int32    `protobuf:"varint,3,req,name=masterId" json:"masterId,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Players) Reset()                    { *m = Players{} }
func (m *Players) String() string            { return proto.CompactTextString(m) }
func (*Players) ProtoMessage()               {}
func (*Players) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Players) GetList() []*Player {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Players) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

func (m *Players) GetMasterId() int32 {
	if m != nil && m.MasterId != nil {
		return *m.MasterId
	}
	return 0
}

type GridStep struct {
	StepInfos        []*GridStep_StepInfo `protobuf:"bytes,1,rep,name=stepInfos" json:"stepInfos,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GridStep) Reset()                    { *m = GridStep{} }
func (m *GridStep) String() string            { return proto.CompactTextString(m) }
func (*GridStep) ProtoMessage()               {}
func (*GridStep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GridStep) GetStepInfos() []*GridStep_StepInfo {
	if m != nil {
		return m.StepInfos
	}
	return nil
}

type GridStep_StepInfo struct {
	NetId            *int32 `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	AddStep          *int32 `protobuf:"varint,2,req,name=addStep" json:"addStep,omitempty"`
	CurStep          *int32 `protobuf:"varint,3,req,name=curStep" json:"curStep,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GridStep_StepInfo) Reset()                    { *m = GridStep_StepInfo{} }
func (m *GridStep_StepInfo) String() string            { return proto.CompactTextString(m) }
func (*GridStep_StepInfo) ProtoMessage()               {}
func (*GridStep_StepInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *GridStep_StepInfo) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *GridStep_StepInfo) GetAddStep() int32 {
	if m != nil && m.AddStep != nil {
		return *m.AddStep
	}
	return 0
}

func (m *GridStep_StepInfo) GetCurStep() int32 {
	if m != nil && m.CurStep != nil {
		return *m.CurStep
	}
	return 0
}

type RollConfirm struct {
	NetId            *int32 `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RollConfirm) Reset()                    { *m = RollConfirm{} }
func (m *RollConfirm) String() string            { return proto.CompactTextString(m) }
func (*RollConfirm) ProtoMessage()               {}
func (*RollConfirm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RollConfirm) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

type BeginShoot struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *BeginShoot) Reset()                    { *m = BeginShoot{} }
func (m *BeginShoot) String() string            { return proto.CompactTextString(m) }
func (*BeginShoot) ProtoMessage()               {}
func (*BeginShoot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CreateMonster struct {
	NetId            *int32 `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	ClientId         *int32 `protobuf:"varint,2,req,name=clientId" json:"clientId,omitempty"`
	TargetId         *int32 `protobuf:"varint,3,req,name=targetId" json:"targetId,omitempty"`
	IndexPos         *int32 `protobuf:"varint,4,req,name=indexPos" json:"indexPos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CreateMonster) Reset()                    { *m = CreateMonster{} }
func (m *CreateMonster) String() string            { return proto.CompactTextString(m) }
func (*CreateMonster) ProtoMessage()               {}
func (*CreateMonster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateMonster) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *CreateMonster) GetClientId() int32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *CreateMonster) GetTargetId() int32 {
	if m != nil && m.TargetId != nil {
		return *m.TargetId
	}
	return 0
}

func (m *CreateMonster) GetIndexPos() int32 {
	if m != nil && m.IndexPos != nil {
		return *m.IndexPos
	}
	return 0
}

type PlayerMove struct {
	SendId           *int32    `protobuf:"varint,1,req,name=sendId" json:"sendId,omitempty"`
	NetId            *int32    `protobuf:"varint,2,req,name=netId" json:"netId,omitempty"`
	Pos              *Position `protobuf:"bytes,3,req,name=pos" json:"pos,omitempty"`
	Rot              *Rotation `protobuf:"bytes,4,req,name=rot" json:"rot,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *PlayerMove) Reset()                    { *m = PlayerMove{} }
func (m *PlayerMove) String() string            { return proto.CompactTextString(m) }
func (*PlayerMove) ProtoMessage()               {}
func (*PlayerMove) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PlayerMove) GetSendId() int32 {
	if m != nil && m.SendId != nil {
		return *m.SendId
	}
	return 0
}

func (m *PlayerMove) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *PlayerMove) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *PlayerMove) GetRot() *Rotation {
	if m != nil {
		return m.Rot
	}
	return nil
}

type PlayerAttack struct {
	SendId           *int32 `protobuf:"varint,1,req,name=sendId" json:"sendId,omitempty"`
	NetId            *int32 `protobuf:"varint,2,req,name=netId" json:"netId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerAttack) Reset()                    { *m = PlayerAttack{} }
func (m *PlayerAttack) String() string            { return proto.CompactTextString(m) }
func (*PlayerAttack) ProtoMessage()               {}
func (*PlayerAttack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PlayerAttack) GetSendId() int32 {
	if m != nil && m.SendId != nil {
		return *m.SendId
	}
	return 0
}

func (m *PlayerAttack) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

type PlayerHurt struct {
	SendId           *int32 `protobuf:"varint,1,req,name=sendId" json:"sendId,omitempty"`
	NetId            *int32 `protobuf:"varint,2,req,name=netId" json:"netId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerHurt) Reset()                    { *m = PlayerHurt{} }
func (m *PlayerHurt) String() string            { return proto.CompactTextString(m) }
func (*PlayerHurt) ProtoMessage()               {}
func (*PlayerHurt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PlayerHurt) GetSendId() int32 {
	if m != nil && m.SendId != nil {
		return *m.SendId
	}
	return 0
}

func (m *PlayerHurt) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

type PlayerDead struct {
	SendId           *int32 `protobuf:"varint,1,req,name=sendId" json:"sendId,omitempty"`
	NetId            *int32 `protobuf:"varint,2,req,name=netId" json:"netId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayerDead) Reset()                    { *m = PlayerDead{} }
func (m *PlayerDead) String() string            { return proto.CompactTextString(m) }
func (*PlayerDead) ProtoMessage()               {}
func (*PlayerDead) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PlayerDead) GetSendId() int32 {
	if m != nil && m.SendId != nil {
		return *m.SendId
	}
	return 0
}

func (m *PlayerDead) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

type CreateBullet struct {
	ButtleId         *int32    `protobuf:"varint,1,req,name=buttleId" json:"buttleId,omitempty"`
	Pos              *Position `protobuf:"bytes,2,req,name=pos" json:"pos,omitempty"`
	Rot              *Rotation `protobuf:"bytes,3,req,name=rot" json:"rot,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CreateBullet) Reset()                    { *m = CreateBullet{} }
func (m *CreateBullet) String() string            { return proto.CompactTextString(m) }
func (*CreateBullet) ProtoMessage()               {}
func (*CreateBullet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateBullet) GetButtleId() int32 {
	if m != nil && m.ButtleId != nil {
		return *m.ButtleId
	}
	return 0
}

func (m *CreateBullet) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *CreateBullet) GetRot() *Rotation {
	if m != nil {
		return m.Rot
	}
	return nil
}

type ShowBoss struct {
	Show             *int32 `protobuf:"varint,1,req,name=show" json:"show,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShowBoss) Reset()                    { *m = ShowBoss{} }
func (m *ShowBoss) String() string            { return proto.CompactTextString(m) }
func (*ShowBoss) ProtoMessage()               {}
func (*ShowBoss) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ShowBoss) GetShow() int32 {
	if m != nil && m.Show != nil {
		return *m.Show
	}
	return 0
}

type CleanMonster struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CleanMonster) Reset()                    { *m = CleanMonster{} }
func (m *CleanMonster) String() string            { return proto.CompactTextString(m) }
func (*CleanMonster) ProtoMessage()               {}
func (*CleanMonster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type CreateEffect struct {
	EffectId         *int32    `protobuf:"varint,1,req,name=effectId" json:"effectId,omitempty"`
	Pos              *Position `protobuf:"bytes,2,req,name=pos" json:"pos,omitempty"`
	LocalShow        *int32    `protobuf:"varint,3,req,name=localShow" json:"localShow,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CreateEffect) Reset()                    { *m = CreateEffect{} }
func (m *CreateEffect) String() string            { return proto.CompactTextString(m) }
func (*CreateEffect) ProtoMessage()               {}
func (*CreateEffect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreateEffect) GetEffectId() int32 {
	if m != nil && m.EffectId != nil {
		return *m.EffectId
	}
	return 0
}

func (m *CreateEffect) GetPos() *Position {
	if m != nil {
		return m.Pos
	}
	return nil
}

func (m *CreateEffect) GetLocalShow() int32 {
	if m != nil && m.LocalShow != nil {
		return *m.LocalShow
	}
	return 0
}

type DestoryBoosBullet struct {
	BulletId         *int32 `protobuf:"varint,1,req,name=bulletId" json:"bulletId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DestoryBoosBullet) Reset()                    { *m = DestoryBoosBullet{} }
func (m *DestoryBoosBullet) String() string            { return proto.CompactTextString(m) }
func (*DestoryBoosBullet) ProtoMessage()               {}
func (*DestoryBoosBullet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *DestoryBoosBullet) GetBulletId() int32 {
	if m != nil && m.BulletId != nil {
		return *m.BulletId
	}
	return 0
}

type PlayInfo struct {
	NetId            *int32 `protobuf:"varint,1,req,name=netId" json:"netId,omitempty"`
	Hp               *int32 `protobuf:"varint,2,req,name=hp" json:"hp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlayInfo) Reset()                    { *m = PlayInfo{} }
func (m *PlayInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayInfo) ProtoMessage()               {}
func (*PlayInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PlayInfo) GetNetId() int32 {
	if m != nil && m.NetId != nil {
		return *m.NetId
	}
	return 0
}

func (m *PlayInfo) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func init() {
	proto.RegisterType((*NetId)(nil), "vse.NetId")
	proto.RegisterType((*Player)(nil), "vse.Player")
	proto.RegisterType((*Players)(nil), "vse.Players")
	proto.RegisterType((*GridStep)(nil), "vse.GridStep")
	proto.RegisterType((*GridStep_StepInfo)(nil), "vse.GridStep.StepInfo")
	proto.RegisterType((*RollConfirm)(nil), "vse.RollConfirm")
	proto.RegisterType((*BeginShoot)(nil), "vse.BeginShoot")
	proto.RegisterType((*CreateMonster)(nil), "vse.CreateMonster")
	proto.RegisterType((*PlayerMove)(nil), "vse.PlayerMove")
	proto.RegisterType((*PlayerAttack)(nil), "vse.PlayerAttack")
	proto.RegisterType((*PlayerHurt)(nil), "vse.PlayerHurt")
	proto.RegisterType((*PlayerDead)(nil), "vse.PlayerDead")
	proto.RegisterType((*CreateBullet)(nil), "vse.CreateBullet")
	proto.RegisterType((*ShowBoss)(nil), "vse.ShowBoss")
	proto.RegisterType((*CleanMonster)(nil), "vse.CleanMonster")
	proto.RegisterType((*CreateEffect)(nil), "vse.CreateEffect")
	proto.RegisterType((*DestoryBoosBullet)(nil), "vse.DestoryBoosBullet")
	proto.RegisterType((*PlayInfo)(nil), "vse.PlayInfo")
}

func init() { proto.RegisterFile("battle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x53, 0x41, 0x6f, 0x1a, 0x3d,
	0x10, 0x15, 0x0b, 0x24, 0x64, 0xd8, 0x44, 0xfa, 0x56, 0x9f, 0x22, 0x84, 0xda, 0x26, 0x72, 0x2f,
	0x39, 0xd1, 0x2a, 0xea, 0x29, 0xea, 0xa5, 0x90, 0xaa, 0xe5, 0x90, 0x2a, 0x5a, 0x7a, 0xec, 0xc5,
	0xd9, 0x1d, 0xc2, 0xaa, 0xc6, 0x83, 0xec, 0x81, 0x14, 0xa9, 0xbf, 0xa3, 0xbf, 0xb7, 0xb2, 0xbd,
	0x06, 0x0e, 0xa5, 0x11, 0xbd, 0xcd, 0xf3, 0x9b, 0x99, 0xf7, 0xf6, 0x79, 0x0d, 0xe9, 0x83, 0x64,
	0x56, 0x38, 0x58, 0x18, 0x62, 0xca, 0x9a, 0x2b, 0x8b, 0xfd, 0xb4, 0xa0, 0xf9, 0x9c, 0x74, 0x38,
	0x12, 0x2f, 0xa1, 0xfd, 0x05, 0x79, 0x5c, 0x66, 0xff, 0x43, 0x5b, 0xbb, 0xa2, 0xd7, 0xb8, 0x4c,
	0xae, 0xda, 0x79, 0x00, 0xe2, 0x06, 0x8e, 0xee, 0x95, 0x5c, 0xa3, 0xf9, 0x33, 0x9f, 0xf5, 0xa1,
	0x53, 0xa8, 0x0a, 0xb5, 0x23, 0x12, 0x4f, 0x6c, 0xb0, 0xf8, 0x06, 0xc7, 0x61, 0xd6, 0x66, 0x17,
	0xd0, 0x52, 0x95, 0xe5, 0x5e, 0xe3, 0xb2, 0x79, 0xd5, 0xbd, 0xee, 0x0e, 0x56, 0x16, 0x07, 0x81,
	0xcb, 0x3d, 0xe1, 0xb6, 0x33, 0xb1, 0x54, 0xf5, 0x92, 0x00, 0xdc, 0xf6, 0xb9, 0xb4, 0x8c, 0x66,
	0x5c, 0xf6, 0x9a, 0x61, 0x7b, 0xc4, 0xe2, 0x57, 0x03, 0x3a, 0x9f, 0x4c, 0x55, 0x4e, 0x18, 0x17,
	0xd9, 0x3b, 0x38, 0xb1, 0x8c, 0x8b, 0xb1, 0x9e, 0x92, 0xad, 0x45, 0xce, 0xbd, 0x48, 0xec, 0x18,
	0x4c, 0x6a, 0x3a, 0xdf, 0x36, 0xf6, 0xbf, 0x42, 0x27, 0x1e, 0xef, 0xf9, 0xbc, 0x1e, 0x1c, 0xcb,
	0xd2, 0x2f, 0xa8, 0x8d, 0x45, 0xe8, 0x98, 0x62, 0x69, 0x3c, 0x13, 0x9c, 0x45, 0x28, 0x5e, 0x43,
	0x37, 0x27, 0xa5, 0x46, 0xa4, 0xa7, 0x95, 0x99, 0xef, 0xc9, 0x35, 0x05, 0x18, 0xe2, 0x63, 0xa5,
	0x27, 0x33, 0x22, 0x16, 0x6b, 0x38, 0x1d, 0x19, 0x94, 0x8c, 0x77, 0xa4, 0xdd, 0xe7, 0x1d, 0x1e,
	0xb6, 0xe3, 0x58, 0x9a, 0x47, 0x3f, 0x54, 0x47, 0x15, 0xb1, 0xe3, 0x2a, 0x5d, 0xe2, 0x8f, 0x7b,
	0xb2, 0xbd, 0x56, 0xe0, 0x22, 0x16, 0x3f, 0x01, 0xc2, 0x45, 0xdc, 0xd1, 0x0a, 0xb3, 0x73, 0x38,
	0xb2, 0xa8, 0xcb, 0x8d, 0x70, 0x8d, 0xb6, 0x7e, 0x92, 0x5d, 0x3f, 0x17, 0xd0, 0x5c, 0x90, 0xf5,
	0x72, 0xdd, 0xeb, 0xd3, 0x70, 0xa9, 0x64, 0x2b, 0xae, 0x48, 0xe7, 0x8e, 0x71, 0x0d, 0x86, 0xd8,
	0x6b, 0xc6, 0x86, 0x9c, 0x58, 0x86, 0x06, 0x43, 0x2c, 0xde, 0x43, 0x1a, 0xd4, 0x3f, 0x30, 0xcb,
	0xe2, 0xfb, 0x61, 0xfa, 0xe2, 0x26, 0x7a, 0xff, 0xbc, 0x34, 0xfc, 0xaf, 0xb3, 0xb7, 0x28, 0xcb,
	0x03, 0x67, 0x15, 0xa4, 0xe1, 0xba, 0x86, 0x4b, 0xa5, 0x90, 0x5d, 0xbe, 0x0f, 0x4b, 0xf7, 0xcc,
	0x36, 0xf3, 0x1b, 0x1c, 0x33, 0x4a, 0x9e, 0xcb, 0xa8, 0xb9, 0x37, 0xa3, 0x57, 0xd0, 0x99, 0xcc,
	0xe8, 0x69, 0x48, 0xd6, 0x66, 0x19, 0xb4, 0xec, 0x8c, 0x9e, 0x6a, 0x15, 0x5f, 0x8b, 0x33, 0x48,
	0x47, 0x0a, 0xa5, 0xae, 0xff, 0x1d, 0x51, 0x45, 0x77, 0x1f, 0xa7, 0x53, 0x2c, 0xbc, 0x3b, 0xf4,
	0xd5, 0xd6, 0x5d, 0xc4, 0xcf, 0xbb, 0x7b, 0x01, 0x27, 0x8a, 0x0a, 0xa9, 0x9c, 0x83, 0xfa, 0xbf,
	0xda, 0x1e, 0x88, 0x37, 0xf0, 0xdf, 0x2d, 0x5a, 0x26, 0xb3, 0x1e, 0x12, 0xd9, 0xdd, 0x34, 0x5c,
	0xb5, 0x9b, 0x46, 0xc0, 0xe2, 0x2d, 0x74, 0x5c, 0xea, 0x7f, 0x79, 0x71, 0x67, 0x90, 0xcc, 0xe2,
	0x63, 0x4b, 0x66, 0x8b, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xb4, 0xa0, 0x64, 0xc1, 0x04,
	0x00, 0x00,
}
