// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

package vse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Position struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y,def=0" json:"y,omitempty"`
	Z                *int32 `protobuf:"varint,3,req,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

const Default_Position_Y int32 = 0

func (m *Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return Default_Position_Y
}

func (m *Position) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type Rotation struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	Z                *int32 `protobuf:"varint,3,req,name=z" json:"z,omitempty"`
	W                *int32 `protobuf:"varint,4,req,name=w" json:"w,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Rotation) Reset()                    { *m = Rotation{} }
func (m *Rotation) String() string            { return proto.CompactTextString(m) }
func (*Rotation) ProtoMessage()               {}
func (*Rotation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Rotation) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Rotation) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Rotation) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *Rotation) GetW() int32 {
	if m != nil && m.W != nil {
		return *m.W
	}
	return 0
}

func init() {
	proto.RegisterType((*Position)(nil), "vse.Position")
	proto.RegisterType((*Rotation)(nil), "vse.Rotation")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2b, 0x4e, 0x55, 0x32, 0xe7,
	0xe2, 0x08, 0xc8, 0x2f, 0xce, 0x2c, 0xc9, 0xcc, 0xcf, 0x13, 0xe2, 0xe1, 0x62, 0xac, 0x90, 0x60,
	0x54, 0x60, 0xd2, 0x60, 0x0d, 0x62, 0xac, 0x10, 0xe2, 0xe7, 0x62, 0xac, 0x94, 0x60, 0x52, 0x60,
	0xd4, 0x60, 0xb5, 0x62, 0x34, 0x08, 0x62, 0xac, 0x04, 0x49, 0x57, 0x49, 0x30, 0x43, 0xa4, 0xab,
	0x94, 0x9c, 0xb8, 0x38, 0x82, 0xf2, 0x4b, 0x12, 0xb1, 0x68, 0xe4, 0x81, 0x68, 0x04, 0xf3, 0xd0,
	0x74, 0x81, 0x78, 0xe5, 0x12, 0x2c, 0x10, 0x5e, 0x39, 0x20, 0x00, 0x00, 0xff, 0xff, 0x62, 0xf5,
	0x27, 0x61, 0x90, 0x00, 0x00, 0x00,
}
